# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://new-repodata.github.io'
baseurl: 
title: 'RepoData'
description: 'Archival repository locations data'
email: "bmrgoldman@gmail.com"
permalink: pretty
logo: ""

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/
- title: Acknowledgements
  url: /acknowledgements/
- title: Data Maintenance
  url: /maintenance/
- title: Data Dictionary
  url: /dictionary/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "Blog posts dated October 2017 to June 2019 were originally published at https://repositorydata.wordpress.com."
    feature_text: 
    feature_image: ""
